version: '3.8'

services:
  app:
    image: ${CI_REGISTRY_IMAGE}
    networks:
      - default
      - ext
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}.loadbalancer.server.port=80"

        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_https.service=${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_https.middlewares=secure-headers@file"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_https.entrypoints=https"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_https.tls=true"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_https.tls.certresolver=le"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_http.service=${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_http.middlewares=secure-headers@file"
        - "traefik.http.routers.${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${ENV_NAME}_http.entrypoints=http"        
    # healthcheck:
    #   test: curl -k -f http://localhost/health || exit 1   #need return HTTP/OK
    #   interval: 10s
    #   timeout: 20s
    #   retries: 3
    #   start_period: 20s

networks:
  ext:
    external: true
    name: ingress_external