version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'old_home'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:3306

volumes:
  my-db:
    driver: local
