name: test-install-php-and-up-services

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: [self-hosted, ene-devarm]
    steps:
      - uses: actions/checkout@v2
      - name: list files
        run: ls -al
      
      - name: Set up PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.2'

  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: [self-hosted, ene-devarm]
    steps:
      - uses: actions/checkout@v2
    # Docker Hub image that `container-job` executes in
    container: nginx

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis